"""
Main Package: app_data

Description: The app_data package contains all the modules relating to data generated by the app.
    This includes the database, the classes designed for storing data, and classes that are part
    of the predictive modeling that goes into recommendations.


Modules:
    db.py

Sub Packages:
    analytics
    data_storers

Other Files:
    data
    database_queries.py
    game_data_EDA.ipynb
"""